const Groq = require("groq-sdk");
const { z } = require("zod");
const puppeteer = require('puppeteer')

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY
});

// ---------------- SCHEMAS ----------------

const technicalQuestionSchema = z.object({
  question: z.string(),
  intention: z.string(),
  answer: z.string()
});

const behavioralQuestionSchema = z.object({
  question: z.string(),
  intention: z.string(),
  answer: z.string()
});

const skillGapSchema = z.object({
  skills: z.string(),
  severity: z.enum(["low", "medium", "high"])
});

const preparationPlanSchema = z.object({
  day: z.number(),
  focus: z.string(),
  tasks: z.array(z.string())
});

const interviewReportSchema = z.object({
  matchScore: z.number(),
  technicalQuestions: z.array(technicalQuestionSchema),
  behavioralQuestions: z.array(behavioralQuestionSchema),
  skillGaps: z.array(skillGapSchema),
  preparationPlan: z.array(preparationPlanSchema),
  title: z.string()
});

function extractJsonFromAiResponse(raw) {
  const trimmed = raw.trim();

  const fencedMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (fencedMatch?.[1]) {
    return fencedMatch[1].trim();
  }

  const jsonMatch = trimmed.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    return jsonMatch[0];
  }

  throw new Error("No JSON found");
}

function extractHtmlFieldFromAiResponse(raw) {
  const jsonLikeContent = extractJsonFromAiResponse(raw);
  const htmlMatch = jsonLikeContent.match(/"html"\s*:\s*"([\s\S]*?)"\s*\}\s*$/);

  if (!htmlMatch?.[1]) {
    throw new Error("No html field found");
  }

  return htmlMatch[1]
    .replace(/\\"/g, '"')
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .trim();
}

// ---------------- MAIN FUNCTION ----------------

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

  const prompt = `
Return ONLY valid JSON.

Schema:
{
  "matchScore": number,
  "technicalQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "skillGaps": [
    {
      "skills": "string",
      "severity": "low | medium | high"
    }
  ],
  "preparationPlan": [
    {
      "day": number,
      "focus": "string",
      "tasks": ["string"]
    }
  ],
  "title": "string"
}
  in the "title" put the job title for which the prep plan is.

Job Description:
${jobDescription}

Resume:
${resume}

Self Description:
${selfDescription}
`;

  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [{ role: "user", content: prompt }],
    temperature: 0
  });

  const raw = response.choices[0].message.content;

  // ---------------- SAFE PARSE ----------------

  let parsed;

  try {
    parsed = JSON.parse(extractJsonFromAiResponse(raw));
  } catch (err) {
    console.log("RAW AI RESPONSE:\n", raw);
    throw new Error("Invalid JSON from AI");
  }

  // ---------------- VALIDATION ----------------

  const result = interviewReportSchema.safeParse(parsed);

  if (!result.success) {
    console.log("ZOD ERROR:", result.error);
    throw new Error("Schema validation failed");
  }

  return result.data;
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4',margin:{
    top: '10mm',
    bottom: '10mm',
    left: '4mm',
    right: '4mm'
  } });
  await browser.close();
  return pdfBuffer;
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const resumePdfSchema = z.object({
    html: z.string()
  });

  const prompt = `Generate a resume in HTML format based on the 
      resume: ${resume}
      selfDescription: ${selfDescription}
      jobDescription: ${jobDescription}
  . Return ONLY valid JSON that matches the schema.

Schema:
{
  "html": "string"
}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
  `
  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [{ role: "user", content: prompt }],
    temperature: 0
  });

  const raw = response.choices[0].message.content;
  let jsonContent;

  try {
    jsonContent = JSON.parse(extractJsonFromAiResponse(raw));
  } catch (error) {
    try {
      jsonContent = {
        html: extractHtmlFieldFromAiResponse(raw)
      };
    } catch (fallbackError) {
      console.log("RAW AI RESPONSE:\n", raw);
      throw new Error("Invalid JSON from AI while generating resume PDF");
    }
  }

  const result = resumePdfSchema.safeParse(jsonContent);

  if (!result.success) {
    console.log("ZOD ERROR:", result.error);
    throw new Error("Resume PDF schema validation failed");
  }

  const pdfBuffer = await generatePdfFromHtml(result.data.html);

  return pdfBuffer;

}

module.exports = { generateInterviewReport, generateResumePdf };
